# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0002_author_book_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='lastname',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='0000', max_length=50),
        ),
    ]
