# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageuser', '0003_auto_20171018_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewrating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
